=== GerocsGergo/FEU2E5XML/XMLTaskFeu2e5/XMLSchemaFeu2e5.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

        <!--Elemek ref-hez-->
    <xs:element name="név" type="xs:string" />
    <xs:element name="elérhetőség" type="elérhetőségTípus" />

    <!-- Saját egyszerű típusok meghatározása, megszorítás -->
    <xs:simpleType name="nemTípus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lány" />
            <xs:enumeration value="fiú" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="kedvezményTípus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="normál" />
            <xs:enumeration value="kedvezményes" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="aktívTípus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen" />
            <xs:enumeration value="nem" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="óraIdőTípus">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:minExclusive value="8" />
            <xs:maxExclusive value="15" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="emailTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z]([a-z0-9_.-]*)@[a-z]([a-z0-9_-]*).[a-z]{2,4}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="telefonTípus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([+]?)\d{11}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="értékelésTípus">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--Komplex típusokhoz saját típus meghatározása, sorrendiség, számosság etc. -->
    <xs:complexType name="elérhetőségTípus">
        <xs:sequence>
            <xs:element name="telefonszám" type="telefonTípus" />
            <xs:element name="email" type="emailTípus" minOccurs="1" maxOccurs="5" />    
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="időpontTípus">
        <xs:sequence>
            <xs:element name="dátum" type="xs:date" />
            <xs:element name="kezdet" type="óraIdőTípus" />
            <xs:element name="vég" type="óraIdőTípus" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="diákTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element name="IQ" type="xs:integer" />
            <xs:element name="születési_dátum" type="xs:date" />
            <xs:element name="nem" type="nemTípus" />
        </xs:sequence>
        <xs:attribute name="Dkód" type="xs:integer" use="required" />
        <xs:attribute name="szülő" type="xs:integer" use="required" />
        <xs:attribute name="tagság" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="tagságTípus">
        <xs:all>
            <xs:element name="kezdőnap" type="xs:date" />
            <xs:element name="kedvezmény" type="kedvezményTípus" />
            <xs:element name="aktív" type="aktívTípus" />
        </xs:all>
        <xs:attribute name="Tagkód" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="szülőTípus">
        <xs:sequence>
            <xs:element ref="név" />        
            <xs:element name="születési_év" type="xs:gYear" />
            <xs:element ref="elérhetőség" />
        </xs:sequence>
        <xs:attribute name="Szkód" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="óraTípus">
        <xs:sequence>
            <xs:element name="téma" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="helyszín" type="xs:string" />
            <xs:element name="időpont" type="időpontTípus" />
        </xs:sequence>
        <xs:attribute name="Ókód" type="xs:integer" use="required" />
        <xs:attribute name="tanár" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="részvételTípus">
        <xs:sequence>
            <xs:element name="értékelés" type="értékelésTípus"  />
            <xs:element name="jutalom" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="diák" type="xs:integer" use="required" />
        <xs:attribute name="óra" type="xs:integer" use="required" />
    </xs:complexType>
    <xs:complexType name="tanárTípus">
        <xs:sequence>
            <xs:element ref="név" />
            <xs:element name="szakterület" type="xs:string" minOccurs="0" maxOccurs="1" />        
            <xs:element name="órabér" type="xs:positiveInteger" />
            <xs:element ref="elérhetőség"/>
        </xs:sequence>
        <xs:attribute name="Tankód" type="xs:integer" use="required" />
    </xs:complexType>

    <!-- Gyökérelemtől az elemek felhasználása -->
    <xs:element name="iskola">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="diák" type="diákTípus" minOccurs="0" maxOccurs="100" />
                <xs:element name="tagság" type="tagságTípus" minOccurs="0" maxOccurs="100" />
                <xs:element name="szülő" type="szülőTípus" minOccurs="0" maxOccurs="100" />
                <xs:element name="óra" type="óraTípus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="részvétel" type="részvételTípus" minOccurs="0" maxOccurs="unbounded" />
                <xs:element name="tanár" type="tanárTípus" minOccurs="1" maxOccurs="100" />
            </xs:sequence>
        </xs:complexType>

        <!-- Elsődleges kulcsok -->
        <xs:key name="diák_kulcs">
            <xs:selector xpath="diák" />
            <xs:field xpath="@Dkód" />
        </xs:key>
        <xs:key name="tagság_kulcs">
            <xs:selector xpath="tagság" />
            <xs:field xpath="@Tagkód" />
        </xs:key>
        <xs:key name="szülő_kulcs">
            <xs:selector xpath="szülő" />
            <xs:field xpath="@Szkód" />
        </xs:key>
        <xs:key name="óra_kulcs">
            <xs:selector xpath="óra" />
            <xs:field xpath="@Ókód" />
        </xs:key>
        <xs:key name="tanár_kulcs">
            <xs:selector xpath="tanár" />
            <xs:field xpath="@Tankód" />
        </xs:key>

        <!-- Idegen kulcsok -->
        <xs:keyref name="diák_tagság_kulcs" refer="tagság_kulcs">
            <xs:selector xpath="diák" />
            <xs:field xpath="@tagság" />
        </xs:keyref>
        <xs:keyref name="diák_szülő_kulcs" refer="szülő_kulcs">
            <xs:selector xpath="diák" />
            <xs:field xpath="@szülő" />
        </xs:keyref>
        <xs:keyref name="óra_tanár_kulcs" refer="tanár_kulcs">
            <xs:selector xpath="óra" />
            <xs:field xpath="@tanár" />
        </xs:keyref>
        <xs:keyref name="részvétel_diák_kulcs" refer="diák_kulcs">
            <xs:selector xpath="részvétel" />
            <xs:field xpath="@diák" />
        </xs:keyref>
        <xs:keyref name="részvétel_óra_kulcs" refer="óra_kulcs">
            <xs:selector xpath="részvétel" />
            <xs:field xpath="@óra" />
        </xs:keyref>

        <!-- Az 1:1 kapcsolat megvalósítása -->
        <xs:unique name="diák_tagság_1_1">
            <xs:selector xpath="diák" />
            <xs:field xpath="@tagság" />
        </xs:unique>

    </xs:element>

</xs:schema>

=== GerocsGergo/FEU2E5XML/XMLTaskFeu2e5/XMLFeu2e5.xml
<?xml version="1.0" encoding="UTF-8"?>

<iskola xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
 xs:noNamespaceSchemaLocation="XMLSchemaFeu2e5.xsd">

<!--Diákok-->
<diák Dkód="10" szülő="100" tagság="1000">
    <név>Kiss Attila</név>
    <IQ>90</IQ>
    <születési_dátum>2016-12-17</születési_dátum>
    <nem>fiú</nem>
</diák>
<diák Dkód="11" szülő="110" tagság="1001">
    <név>Nagy Mária</név>
    <IQ>65</IQ>
    <születési_dátum>2016-10-15</születési_dátum>
    <nem>lány</nem>
</diák>
<diák Dkód="12" szülő="120" tagság="1002">
    <név>Szép Tamás</név>
    <IQ>110</IQ>
    <születési_dátum>2016-06-06</születési_dátum>
    <nem>fiú</nem>
</diák>
<diák Dkód="13" szülő="120" tagság="1003">
    <név>Szép Anita</név>
    <IQ>115</IQ>
    <születési_dátum>2016-01-05</születési_dátum>
    <nem>lány</nem>
</diák>

<!--tagság adatok-->
<tagság Tagkód="1000">
    <kezdőnap>2016-09-01</kezdőnap>
    <kedvezmény>normál</kedvezmény>
    <aktív>igen</aktív>
</tagság>
<tagság Tagkód="1001">
    <kezdőnap>2015-09-01</kezdőnap>
    <kedvezmény>kedvezményes</kedvezmény>
    <aktív>igen</aktív>
</tagság>
<tagság Tagkód="1002">
    <kezdőnap>2013-09-01</kezdőnap>
    <kedvezmény>normál</kedvezmény>
    <aktív>igen</aktív>
</tagság>
<tagság Tagkód="1003">
    <kezdőnap>2013-09-01</kezdőnap>
    <kedvezmény>kedvezményes</kedvezmény>
    <aktív>nem</aktív>
</tagság>

<!--szülők-->
<szülő Szkód="100">
    <név>Kiss Béla</név>
    <születési_év>1985</születési_év>
    <elérhetőség>
        <telefonszám>+36506060768</telefonszám>
        <email>belakiss@gmail.com</email>
        <email>kissbela@citromail.hu</email>
    </elérhetőség>
</szülő>
<szülő Szkód="110">
    <név>Nagy Adrienn</név>
    <születési_év>1991</születési_év>
    <elérhetőség>
        <telefonszám>+36701234987</telefonszám>
        <email>n.adrienn@gmail.com</email>
    </elérhetőség>
</szülő>
<szülő Szkód="120">
    <név>Szép János</név>
    <születési_év>1990</születési_év>
    <elérhetőség>
        <telefonszám>+36208877665</telefonszám>
        <email>szepjancsi@szepmail.hu</email>
        <email>jancsi.szep@gmail.com</email>
        <email>jancsi.szep@freemail.com</email>
    </elérhetőség>
</szülő>
<!--Órák-->
<óra Ókód="1200" tanár="1100">
    <téma>Matematika alapjai</téma>
    <helyszín>tanterem 101.</helyszín>
    <időpont>
        <dátum>2024-10-30</dátum>
        <kezdet>13</kezdet>
        <vég>14</vég>
    </időpont>
</óra>
<óra Ókód="1201" tanár="1100">
    <téma>osztás</téma>
    <téma>szorzás</téma>
    <helyszín>tanterem 2.</helyszín>
    <időpont>
        <dátum>2024-10-15</dátum>
        <kezdet>9</kezdet>
        <vég>10</vég>
    </időpont>
</óra>
<óra Ókód="1202" tanár="1101">
    <téma>Kidobós</téma>
    <téma>cooper teszt</téma>
    <helyszín>tornaterem</helyszín>
    <időpont>
        <dátum>2024-09-02</dátum>
        <kezdet>12</kezdet>
        <vég>13</vég>
    </időpont>
</óra>
<óra Ókód="1203" tanár="1102">
    <téma>fogócska</téma>
    <helyszín>udvar</helyszín>
    <időpont>
        <dátum>2024-11-25</dátum>
        <kezdet>11</kezdet>
        <vég>12</vég>
    </időpont>
</óra>

<!--Részvételi adatok-->
<részvétel diák="10" óra="1200">
    <értékelés>3</értékelés>
</részvétel>
<részvétel diák="10" óra="1201">
    <értékelés>4</értékelés>
    <jutalom>pirospont</jutalom>
</részvétel>
<részvétel diák="11" óra="1201">
    <értékelés>5</értékelés>
    <jutalom>matrica</jutalom>
</részvétel>
<részvétel diák="12" óra="1200">
    <értékelés>1</értékelés>
    <jutalom>feketepont</jutalom>
</részvétel>
<részvétel diák="12" óra="1202">
    <értékelés>3</értékelés>
</részvétel>
<részvétel diák="13" óra="1203">
    <értékelés>5</értékelés>
    <jutalom>pirospont</jutalom>
</részvétel>

<!--tanárok-->
<tanár Tankód="1100">
    <név>Takács Péter</név>
    <szakterület>Matematika</szakterület>
    <órabér>5000</órabér>
    <elérhetőség>
        <telefonszám>+36702525625</telefonszám>
        <email>t.p@gmail.com</email>
    </elérhetőség>
</tanár>
<tanár Tankód="1101">
    <név>Kovács Zoltán</név>
    <szakterület>Testnevelés</szakterület>
    <órabér>2500</órabér>
    <elérhetőség>
        <telefonszám>+36301233456</telefonszám>
        <email>kovizol@gmail.com</email>
        <email>kovacs.z@freemail.hu</email>
    </elérhetőség>
</tanár>
<tanár Tankód="1102">
    <név>Lédig Anna</név>
    <szakterület>Viselkedés Pszichológia</szakterület>
    <órabér>9500</órabér>
    <elérhetőség>
        <telefonszám>+36708996574</telefonszám>
        <email>ledig@gmail.com</email>
    </elérhetőség>
</tanár>


 </iskola>
